version: "3.9"

services:
  client:
    container_name: frontend_web
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    expose:
      - "80"
    volumes:
      - frontend:/usr/src/app
    networks:
      - frontend_net
    depends_on:
      - server
  server:
    container_name: backend_server
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - DB_NAME=test_db_1
      - DB_USER=root
      - DB_PASS=test1223
      - DB_HOST=localhost
    volumes:
      - backend:/usr/src/app
    networks:
      - backend_net
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test1223
      - MYSQL_PASSWORD=test1223
      - MYSQL_DATABASE=test_db_1
      - MYSQL_USER=user1
    volumes:
      - ./data:/var/lib/mysql
  proxy:
    image: nginx:alpine
    container_name: app-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - client

networks:
  frontend_net:
  backend_net:
    driver: bridge

volumes:
  frontend:
  backend:
