version: '3.9'

services:
  client:
    container_name: frontend_web
    restart: always
    build: .
    ports:
      -"3000:3000"
    volumes:
      - frontend:/usr/src/app
    networks:
      - frontend_net
  server:
    container_name: backend_server
    restart: always
    build: .
    ports:
      -"5000:5000"
    volumes:
      - backend:/usr/src/app
    networks:
      - backend_net

networks:
  frontend_net:
  backend_net:
    
volumes:
  frontend:
  backend:
